service: valorant-stream-helper

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  app:
    handler: handler.handler
    memorySize: 512
    timeout: 30
    events:
      - http: ANY /
      - http: ANY /{proxy+}

# llingMode: PAY_PER_REQUEST

custom:
  deployConcurrency: 1
  logRetentionInDays: 7
  prune:
    automatic: true
    number: 3

# custom:
#   esbuild:
#     bundle: true
#     target: "node18"
#     platform: "node"
#     external:
#       - aws-sdk

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  - serverless-prune-plugin
  # - serverless-esbuild
